# Generated by Django 5.2.4 on 2025-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylog_group_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('group_creation', 'Group Creation'), ('group_deletion', 'Group Deletion'), ('expense_creation', 'Expense Creation'), ('expense_update', 'Expense Update'), ('settlement', 'Settlement'), ('member_joined', 'Member Joined'), ('member_removal', 'Member Removal'), ('invite_sent', 'Invite Sent'), ('invite_accepted', 'Invite Accepted')], help_text='The type of activity logged', max_length=50),
        ),
    ]
