# Generated by Django 5.2.4 on 2025-07-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total_amount_order_updated_at_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
