# Generated by Django 5.2.4 on 2025-08-08 08:03

import django.db.models.deletion
import groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_alter_groupuser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(default=groups.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(default='NPR', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email', 'group'), name='unique_pending_invite_per_group'),
        ),
    ]
