# Generated by Django 5.2.4 on 2025-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupinvite_delete_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
