# Generated by Django 5.2.4 on 2025-08-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensehistory',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensehistory',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseHistory',
        ),
    ]
